# ==================== Server Configuration ====================
server.port=${SERVER_PORT:8084}
server.servlet.context-path=/api/v1

# ==================== Database Configuration ====================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/edulearn_enrollment?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

# ==================== JPA/Hibernate Configuration ====================
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

# ==================== JWT Configuration ====================
jwt.secret=${JWT_SECRET:mySecretKeyForJWTAuthenticationInEduLearnMicroserviceArchitecture2024SuperSecureKey123!@#}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ==================== Application Name ====================
spring.application.name=enrollment-service

# ==================== Logging Configuration ====================
logging.level.root=INFO
logging.level.com.edulearn.enrollment=DEBUG



# 1. Trust the package coming from the Payment Service
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# 2. Map the "Remote" class name to your "Local" class name
# Format: RemoteClassName:LocalFullClassName
spring.kafka.consumer.properties.spring.json.type.mapping=com.edulearn.payment.entity.PaymentSuccessEvent:com.edulearn.enrollment.entity.PaymentSuccessEvent


spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# ==================== Eureka Client Configuration ====================
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true