spring.application.name=Discovery-Server


eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

server.port=${SERVER_PORT:8761}

# ==================== Actuator Health Checks ====================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
